spring.application.name=AlgaFoodAPI

# database config #
spring.datasource.url=jdbc:mysql://localhost:3306/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

# configuração do schema #
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/ddl.sql

# Configuração das migrations #
spring.flyway.locations=classpath:db/migration,classpath:db/testdata


#Configuração da desserialização JSON -> java #
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true
#spring.jackson.property-naming-strategy=SNAKE_CASE

#lança exceção se não encontrar end point procurado #
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false


